### PR TITLE
Refine the default unit tests

### LINKED ISSUE #44: Default unit test for doesn't test anything
_by @hf-kklein in https://github.com/Microsoft/vscode-azurefunctions/issues/491#issue-346877658_:

Steps to reproduce:
* create a new Azure Function Project using the [Azure Function VS Code PlugIn](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) . Choose language Java and default values.
* The path `src\test\java\com\function\FunctionTest.java` contains an autogenerated unit test for the Function class in `src\main\java\com\function\Function.java`.
* One would expect the test to fail, if the HTTP status code of the repsonse generated by the Azure Function inside the Function class returns something is different from 200 -- OK. 
* Run original test => passed;
* Modify the Azure Function `HttpTriggerJava` in Function´.java:
replace this part (lines 26-30)
```java
if (name == null) {
     return request.createResponse(400, "Please pass a name on the query string or in the request body");
} else {
     return request.createResponse(200, "Hello, " + name);
}
```
with this:
```java
return request.createResponse(500, "This unit test is pointless");
```
* Run test again => still passes.

By default you're mocking _all_ characteristics of the response. Except for the case when the function returns `null`, the test can never fail.

### PR DESCRIPTION
**Pull request by jdneo**
Resolve #44 

As mentioned in #44, the default unit tests actually test nothing there, since it just verifies whether the Function will return the same object as we set in the mock setup.

A better approach could be returning a real mocked `HttpResponseMessage` and verify whether the status code is the same. We leverage `doAnswer()` API to achieve this.

### CODE REVIEW

File: azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/HttpResponseMessageMock.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
+package $package;
+
+import com.microsoft.azure.functions.*;
+
+import java.util.Map;
+public class HttpResponseMessageMock implements HttpResponseMessage {
```
Comment (xscript) [inline azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/HttpResponseMessageMock.java]: New line and comments?

**Comment by jdneo** [comment]
@pragnagopa Please take a look about this PR when you have time.

I'm thinking that one risk here might be that the implementation of the HttpResponseMessageMock is different from the real implementation， which may cause the unit tests to become meaningless again.
